// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "heex",
		Extensions:     []string{".heex"},
		Language:       HeexLanguage,
		HighlightQuery: heexHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("heex"),
	})
}

const heexHighlightQuery = "; General HEEx delimiters\n[\n  \"<\"\n  \"<!\"\n  \"</\"\n  \"<:\"\n  \"</:\"\n  \">\"\n  \"/>\"\n  \"{\"\n  \"}\"\n] @punctuation.bracket\n\n; HEEx directive expressions can use the following tag delimiters:\n;     `<%` and `%>`\n;     `<%=` and `%>`\n;     `<%%` and `%>`\n;     `<%%=` and `%>`\n(directive) @keyword\n\n; HEEx comments can use the following tag delimiters:\n;     `<!--` and `-->`\n;     `<%!--` and `--%>`\n;     `<%#` and `%>`\n(comment) @comment\n\n; HEEx operators are highlighted as such\n\"=\" @operator\n\n; HEEx entities are highligted as special strings\n(entity) @string.special\n\n; HEEx inherits the DOCTYPE tag from HTML\n(doctype) @constant\n\n; Tree-sitter parser errors\n(ERROR) @error\n\n; HEEx tags and slots are highlighted as HTML tags\n[\n  (tag_name)\n  (slot_name)\n] @tag\n\n; HEEx components are highlighted as Elixir modules and functions\n(component_name\n  [\n    (module) @module\n    (function) @function\n    \".\" @punctuation.delimiter\n  ])\n\n; HEEx attributes are highlighted as HTML attributes\n(attribute_name) @attribute\n\n; HEEx special attributes can be any of the following:\n;     `:let`\n;     `:if`\n;     `:for`\n;     `:key`\n;     `:stream`\n(special_attribute_name) @keyword\n\n; HEEx attribute values are highlighted as HTML attribute values\n[\n  (attribute_value)\n  (quoted_attribute_value)\n] @string\n"
