// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:           "qmljs",
		Extensions:     []string{".qml"},
		Language:       QmljsLanguage,
		HighlightQuery: qmljsHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("qmljs"),
	})
}

const qmljsHighlightQuery = ";;; Annotations\n\n(ui_annotation\n  \"@\" @operator\n  type_name: [\n    (identifier) @attribute\n    (nested_identifier (identifier) @attribute)\n  ])\n\n;;; Properties\n\n(ui_object_definition_binding\n  name: [\n    (identifier) @property\n    (nested_identifier (identifier) @property)\n  ])\n\n(ui_binding\n  name: [\n    (identifier) @property\n    (nested_identifier (identifier) @property)\n  ])\n\n;; locals query appears not working unless id: <ref> isn't a parameter.\n(ui_binding\n  name: (identifier) @property\n  (#eq? @property \"id\")\n  value: (expression_statement (identifier) @variable.parameter))\n\n(ui_property\n  name: (identifier) @property)\n\n(ui_required\n  name: (identifier) @property)\n\n(ui_list_property_type\n  [\"<\" \">\"] @punctuation.bracket)\n\n;;; Signals\n\n(ui_signal\n  name: (identifier) @function.signal)\n\n(ui_signal_parameter\n  (identifier) @variable.parameter)\n\n;;; Keywords\n\n[\n  \"as\"\n  \"component\"\n  \"default\"\n  \"final\"\n  \"import\"\n  \"on\"\n  \"override\"\n  \"pragma\"\n  \"property\"\n  \"readonly\"\n  \"required\"\n  \"signal\"\n  \"virtual\"\n] @keyword\n"
