//go:build legacy_generated_register_stubs

// Code generated by ts2go batch. DO NOT EDIT.

package grammars

func init() {
	Register(LangEntry{
		Name:               "qmljs",
		Extensions:         []string{".qml"},
		Language:           QmljsLanguage,
		HighlightQuery:     qmljsHighlightQuery,
		TokenSourceFactory: defaultTokenSourceFactory("qmljs"),
	})
}
