// Code generated by danmuji — DO NOT EDIT.

package grammargen

import (
	"github.com/odvcencio/gotreesitter"
	"github.com/odvcencio/gotreesitter/grammars"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"os"
	"testing"
)

func TestFortranParity(t *testing.T) {
//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:11
	t.Parallel()
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:30
t.Run("integer kind suffix in expression", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:31
t.Run("parsing 1_SZ1 identifier kind", func(t *testing.T) {
			src := "program t\n  int_val = 1_SZ1\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:35
t.Run("parse succeeds without errors", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:36
require.NoError(t, perr, "danmuji:36: given integer kind suffix in expression > when parsing 1_SZ1 identifier kind > then parse succeeds without errors | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:37
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:37: given integer kind suffix in expression > when parsing 1_SZ1 identifier kind > then parse succeeds without errors | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:41
t.Run("parsing 1_4 numeric kind", func(t *testing.T) {
			src := "program t\n  int_val = 1_4\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:45
t.Run("parse succeeds without errors", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:46
require.NoError(t, perr, "danmuji:46: given integer kind suffix in expression > when parsing 1_4 numeric kind > then parse succeeds without errors | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:47
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:47: given integer kind suffix in expression > when parsing 1_4 numeric kind > then parse succeeds without errors | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:52
t.Run("parametric derived type with type parameters", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:53
t.Run("parsing type with two parameters", func(t *testing.T) {
			src := "program test\n  type, abstract :: matrix(k, d)\n    integer :: x\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:57
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:58
require.NoError(t, perr, "danmuji:58: given parametric derived type with type parameters > when parsing type with two parameters > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:59
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:59: given parametric derived type with type parameters > when parsing type with two parameters > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:63
t.Run("parsing type with single parameter", func(t *testing.T) {
			src := "program test\n  type :: vec(n)\n    integer :: x\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:67
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:68
require.NoError(t, perr, "danmuji:68: given parametric derived type with type parameters > when parsing type with single parameter > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:69
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:69: given parametric derived type with type parameters > when parsing type with single parameter > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:74
t.Run("call expression with infix division", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:75
t.Run("parsing f(x)/g(y)", func(t *testing.T) {
			src := "program t\n  real :: z\n  z = f(x) / g(y)\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:79
t.Run("parse succeeds with math_expression wrapping calls", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:80
require.NoError(t, perr, "danmuji:80: given call expression with infix division > when parsing f(x)/g(y) > then parse succeeds with math_expression wrapping calls | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:81
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:81: given call expression with infix division > when parsing f(x)/g(y) > then parse succeeds with math_expression wrapping calls | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:86
t.Run("array subscripts with extent specifiers", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:87
t.Run("parsing xij(:, :)", func(t *testing.T) {
			src := "program t\n  real :: xij(:, :)\nend program t\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:91
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:92
require.NoError(t, perr, "danmuji:92: given array subscripts with extent specifiers > when parsing xij(:, :) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:93
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:93: given array subscripts with extent specifiers > when parsing xij(:, :) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:97
t.Run("parsing Val(:)", func(t *testing.T) {
			src := "program t\n  real :: Val(:)\nend program t\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:101
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:102
require.NoError(t, perr, "danmuji:102: given array subscripts with extent specifiers > when parsing Val(:) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:103
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:103: given array subscripts with extent specifiers > when parsing Val(:) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:108
t.Run("generated Fortran grammar lex modes", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:109
t.Run("verifying lex mode completeness", func(t *testing.T) {
			_ = parser
			mismatches := VerifyLexModeCompleteness(lang)

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:113
t.Run("no states have action-table terminals missing from lex mode", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:114
assert.True(t, len(mismatches) <= 2, "danmuji:114: given generated Fortran grammar lex modes > when verifying lex mode completeness > then no states have action-table terminals missing from lex mode | expect (expect len(mismatches) <= 2)")
			})
		})
})
}

