// Code generated by danmuji — DO NOT EDIT.

package grammargen

import (
	"github.com/odvcencio/gotreesitter"
	"github.com/odvcencio/gotreesitter/grammars"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"os"
	"testing"
)

func TestFortranParity(t *testing.T) {
//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:11
	t.Parallel()
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:30
t.Run("integer kind suffix in expression", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:31
t.Run("parsing 1_SZ1 identifier kind", func(t *testing.T) {
			src := "program t\n  int_val = 1_SZ1\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:35
t.Run("parse succeeds without errors", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:36
require.NoError(t, perr, "danmuji:36: given integer kind suffix in expression > when parsing 1_SZ1 identifier kind > then parse succeeds without errors | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:37
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:37: given integer kind suffix in expression > when parsing 1_SZ1 identifier kind > then parse succeeds without errors | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:41
t.Run("parsing 1_4 numeric kind", func(t *testing.T) {
			src := "program t\n  int_val = 1_4\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:45
t.Run("parse succeeds without errors", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:46
require.NoError(t, perr, "danmuji:46: given integer kind suffix in expression > when parsing 1_4 numeric kind > then parse succeeds without errors | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:47
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:47: given integer kind suffix in expression > when parsing 1_4 numeric kind > then parse succeeds without errors | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:52
t.Run("parametric derived type with type parameters", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:53
t.Run("parsing type with two parameters", func(t *testing.T) {
			src := "program test\n  type, abstract :: matrix(k, d)\n    integer :: x\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:57
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:58
require.NoError(t, perr, "danmuji:58: given parametric derived type with type parameters > when parsing type with two parameters > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:59
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:59: given parametric derived type with type parameters > when parsing type with two parameters > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:63
t.Run("parsing type with single parameter", func(t *testing.T) {
			src := "program test\n  type :: vec(n)\n    integer :: x\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:67
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:68
require.NoError(t, perr, "danmuji:68: given parametric derived type with type parameters > when parsing type with single parameter > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:69
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:69: given parametric derived type with type parameters > when parsing type with single parameter > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:74
t.Run("call expression with infix division", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:75
t.Run("parsing f(x)/g(y)", func(t *testing.T) {
			src := "program t\n  real :: z\n  z = f(x) / g(y)\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:79
t.Run("parse succeeds with math_expression wrapping calls", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:80
require.NoError(t, perr, "danmuji:80: given call expression with infix division > when parsing f(x)/g(y) > then parse succeeds with math_expression wrapping calls | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:81
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:81: given call expression with infix division > when parsing f(x)/g(y) > then parse succeeds with math_expression wrapping calls | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:86
t.Run("array subscripts with extent specifiers", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:87
t.Run("parsing xij(:, :)", func(t *testing.T) {
			src := "program t\n  real :: xij(:, :)\nend program t\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:91
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:92
require.NoError(t, perr, "danmuji:92: given array subscripts with extent specifiers > when parsing xij(:, :) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:93
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:93: given array subscripts with extent specifiers > when parsing xij(:, :) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:97
t.Run("parsing Val(:)", func(t *testing.T) {
			src := "program t\n  real :: Val(:)\nend program t\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:101
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:102
require.NoError(t, perr, "danmuji:102: given array subscripts with extent specifiers > when parsing Val(:) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:103
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:103: given array subscripts with extent specifiers > when parsing Val(:) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:108
t.Run("generated Fortran grammar lex modes", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:109
t.Run("verifying lex mode completeness", func(t *testing.T) {
			_ = parser
			mismatches := VerifyLexModeCompleteness(lang)

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:113
t.Run("no states have action-table terminals missing from lex mode", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:114
assert.True(t, len(mismatches) <= 2, "danmuji:114: given generated Fortran grammar lex modes > when verifying lex mode completeness > then no states have action-table terminals missing from lex mode | expect (expect len(mismatches) <= 2)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:119
t.Run("labeled block constructs", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:120
t.Run("parsing labeled DO loop with numeric statement label", func(t *testing.T) {
			src := "program test\n  do 10 i = 1, 10\n    foo(i) = i\n10 continue\nend program test\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:124
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:125
require.NoError(t, perr, "danmuji:125: given labeled block constructs > when parsing labeled DO loop with numeric statement label > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:126
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:126: given labeled block constructs > when parsing labeled DO loop with numeric statement label > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:130
t.Run("parsing labeled WHERE block", func(t *testing.T) {
			src := "program test\ncond1: WHERE(PRESSURE .GE. 1.0)\n  PRESSURE = PRESSURE + 1.0\nENDWHERE cond1\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:134
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:135
require.NoError(t, perr, "danmuji:135: given labeled block constructs > when parsing labeled WHERE block > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:136
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:136: given labeled block constructs > when parsing labeled WHERE block > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:140
t.Run("parsing labeled DO block with CYCLE", func(t *testing.T) {
			src := "PROGRAM TEST\n  out44: DO i = 1,10\n    CYCLE out44\n  END DO out44\nEND PROGRAM\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:144
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:145
require.NoError(t, perr, "danmuji:145: given labeled block constructs > when parsing labeled DO block with CYCLE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:146
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:146: given labeled block constructs > when parsing labeled DO block with CYCLE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:150
t.Run("parsing labeled IF block", func(t *testing.T) {
			src := "PROGRAM TEST\n  cond1: IF (y < 0) THEN\n    y = 9\n  END IF cond1\nEND PROGRAM\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:154
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:155
require.NoError(t, perr, "danmuji:155: given labeled block constructs > when parsing labeled IF block > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:156
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:156: given labeled block constructs > when parsing labeled IF block > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Control: unlabeled SELECT CASE is expected to already parse.
	// If this test fails, the end-of-block conflict is not label-specific.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:162
t.Run("parsing unlabeled SELECT CASE", func(t *testing.T) {
			src := "program t\n  SELECT CASE (n)\n  CASE DEFAULT\n    m = 0\n  END SELECT\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:166
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:167
require.NoError(t, perr, "danmuji:167: given labeled block constructs > when parsing unlabeled SELECT CASE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:168
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:168: given labeled block constructs > when parsing unlabeled SELECT CASE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Failing repro (as of 2026-04-11): unlabeled SELECT TYPE with
	// type is / class default bodies. Baseline sample 11 essence.
	// Triggers body-statement-vs-end_select_statement conflict on `end`.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:175
t.Run("parsing unlabeled SELECT TYPE", func(t *testing.T) {
			src := "program t\n  select type(x)\n    type is (integer)\n      y = 1\n    class default\n      y = 0\n  end select\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:179
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:180
require.NoError(t, perr, "danmuji:180: given labeled block constructs > when parsing unlabeled SELECT TYPE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:181
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:181: given labeled block constructs > when parsing unlabeled SELECT TYPE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Failing repro (as of 2026-04-11): labeled SELECT CASE. Baseline
	// sample 13 essence, minimized. The trailing `sign_case` after
	// END SELECT is the key signal — parser must keep `end select`
	// shift path alive rather than reducing the inner statement list
	// with `end` as a trailing identifier.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:190
t.Run("parsing labeled SELECT CASE", func(t *testing.T) {
			src := "program t\n  sign_case: SELECT CASE (n)\n  CASE DEFAULT\n    m = 0\n  END SELECT sign_case\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:194
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:195
require.NoError(t, perr, "danmuji:195: given labeled block constructs > when parsing labeled SELECT CASE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:196
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:196: given labeled block constructs > when parsing labeled SELECT CASE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Failing repro (as of 2026-04-11): labeled SELECT TYPE. Combined
	// shape for the split oracle fix target — if this passes, both s11
	// and s13 shapes are covered by the same state split.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:203
t.Run("parsing labeled SELECT TYPE", func(t *testing.T) {
			src := "program t\n  sel: select type(x)\n    type is (integer)\n      y = 1\n  end select sel\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:207
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:208
require.NoError(t, perr, "danmuji:208: given labeled block constructs > when parsing labeled SELECT TYPE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:209
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:209: given labeled block constructs > when parsing labeled SELECT TYPE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:214
t.Run("generic operator bindings", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:215
t.Run("parsing assignment(=) generic", func(t *testing.T) {
			src := "program test\n  type, public :: t\n    real :: x\n    contains\n       generic, private :: assignment(=) => assign_method\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:219
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:220
require.NoError(t, perr, "danmuji:220: given generic operator bindings > when parsing assignment(=) generic > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:221
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:221: given generic operator bindings > when parsing assignment(=) generic > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:225
t.Run("parsing operator(+) generic", func(t *testing.T) {
			src := "program test\n  type, public :: t\n    real :: x\n    contains\n       generic, private :: operator(+) => add_method\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:229
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:230
require.NoError(t, perr, "danmuji:230: given generic operator bindings > when parsing operator(+) generic > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:231
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:231: given generic operator bindings > when parsing operator(+) generic > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
}

