// Code generated by danmuji — DO NOT EDIT.

package grammargen

import (
	"github.com/odvcencio/gotreesitter"
	"github.com/odvcencio/gotreesitter/grammars"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"os"
	"testing"
)

func TestFortranParity(t *testing.T) {
//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:11
	t.Parallel()
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:30
t.Run("integer kind suffix in expression", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:31
t.Run("parsing 1_SZ1 identifier kind", func(t *testing.T) {
			src := "program t\n  int_val = 1_SZ1\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:35
t.Run("parse succeeds without errors", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:36
require.NoError(t, perr, "danmuji:36: given integer kind suffix in expression > when parsing 1_SZ1 identifier kind > then parse succeeds without errors | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:37
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:37: given integer kind suffix in expression > when parsing 1_SZ1 identifier kind > then parse succeeds without errors | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:41
t.Run("parsing 1_4 numeric kind", func(t *testing.T) {
			src := "program t\n  int_val = 1_4\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:45
t.Run("parse succeeds without errors", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:46
require.NoError(t, perr, "danmuji:46: given integer kind suffix in expression > when parsing 1_4 numeric kind > then parse succeeds without errors | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:47
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:47: given integer kind suffix in expression > when parsing 1_4 numeric kind > then parse succeeds without errors | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:52
t.Run("parametric derived type with type parameters", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:53
t.Run("parsing type with two parameters", func(t *testing.T) {
			src := "program test\n  type, abstract :: matrix(k, d)\n    integer :: x\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:57
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:58
require.NoError(t, perr, "danmuji:58: given parametric derived type with type parameters > when parsing type with two parameters > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:59
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:59: given parametric derived type with type parameters > when parsing type with two parameters > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:63
t.Run("parsing type with single parameter", func(t *testing.T) {
			src := "program test\n  type :: vec(n)\n    integer :: x\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:67
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:68
require.NoError(t, perr, "danmuji:68: given parametric derived type with type parameters > when parsing type with single parameter > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:69
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:69: given parametric derived type with type parameters > when parsing type with single parameter > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:74
t.Run("call expression with infix division", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:75
t.Run("parsing f(x)/g(y)", func(t *testing.T) {
			src := "program t\n  real :: z\n  z = f(x) / g(y)\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:79
t.Run("parse succeeds with math_expression wrapping calls", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:80
require.NoError(t, perr, "danmuji:80: given call expression with infix division > when parsing f(x)/g(y) > then parse succeeds with math_expression wrapping calls | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:81
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:81: given call expression with infix division > when parsing f(x)/g(y) > then parse succeeds with math_expression wrapping calls | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:86
t.Run("array subscripts with extent specifiers", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:87
t.Run("parsing xij(:, :)", func(t *testing.T) {
			src := "program t\n  real :: xij(:, :)\nend program t\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:91
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:92
require.NoError(t, perr, "danmuji:92: given array subscripts with extent specifiers > when parsing xij(:, :) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:93
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:93: given array subscripts with extent specifiers > when parsing xij(:, :) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:97
t.Run("parsing Val(:)", func(t *testing.T) {
			src := "program t\n  real :: Val(:)\nend program t\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:101
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:102
require.NoError(t, perr, "danmuji:102: given array subscripts with extent specifiers > when parsing Val(:) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:103
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:103: given array subscripts with extent specifiers > when parsing Val(:) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:108
t.Run("generated Fortran grammar lex modes", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:109
t.Run("verifying lex mode completeness", func(t *testing.T) {
			_ = parser
			mismatches := VerifyLexModeCompleteness(lang)

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:113
t.Run("no states have action-table terminals missing from lex mode", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:114
assert.True(t, len(mismatches) <= 2, "danmuji:114: given generated Fortran grammar lex modes > when verifying lex mode completeness > then no states have action-table terminals missing from lex mode | expect (expect len(mismatches) <= 2)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:119
t.Run("labeled block constructs", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:120
t.Run("parsing labeled DO loop with numeric statement label", func(t *testing.T) {
			src := "program test\n  do 10 i = 1, 10\n    foo(i) = i\n10 continue\nend program test\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:124
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:125
require.NoError(t, perr, "danmuji:125: given labeled block constructs > when parsing labeled DO loop with numeric statement label > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:126
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:126: given labeled block constructs > when parsing labeled DO loop with numeric statement label > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:130
t.Run("parsing labeled WHERE block", func(t *testing.T) {
			src := "program test\ncond1: WHERE(PRESSURE .GE. 1.0)\n  PRESSURE = PRESSURE + 1.0\nENDWHERE cond1\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:134
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:135
require.NoError(t, perr, "danmuji:135: given labeled block constructs > when parsing labeled WHERE block > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:136
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:136: given labeled block constructs > when parsing labeled WHERE block > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:140
t.Run("parsing labeled DO block with CYCLE", func(t *testing.T) {
			src := "PROGRAM TEST\n  out44: DO i = 1,10\n    CYCLE out44\n  END DO out44\nEND PROGRAM\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:144
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:145
require.NoError(t, perr, "danmuji:145: given labeled block constructs > when parsing labeled DO block with CYCLE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:146
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:146: given labeled block constructs > when parsing labeled DO block with CYCLE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:150
t.Run("parsing labeled IF block", func(t *testing.T) {
			src := "PROGRAM TEST\n  cond1: IF (y < 0) THEN\n    y = 9\n  END IF cond1\nEND PROGRAM\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:154
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:155
require.NoError(t, perr, "danmuji:155: given labeled block constructs > when parsing labeled IF block > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:156
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:156: given labeled block constructs > when parsing labeled IF block > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Control: unlabeled SELECT CASE is expected to already parse.
	// If this test fails, the end-of-block conflict is not label-specific.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:162
t.Run("parsing unlabeled SELECT CASE", func(t *testing.T) {
			src := "program t\n  SELECT CASE (n)\n  CASE DEFAULT\n    m = 0\n  END SELECT\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:166
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:167
require.NoError(t, perr, "danmuji:167: given labeled block constructs > when parsing unlabeled SELECT CASE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:168
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:168: given labeled block constructs > when parsing unlabeled SELECT CASE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Failing repro (as of 2026-04-11): unlabeled SELECT TYPE with
	// type is / class default bodies. Baseline sample 11 essence.
	// Triggers body-statement-vs-end_select_statement conflict on `end`.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:175
t.Run("parsing unlabeled SELECT TYPE", func(t *testing.T) {
			src := "program t\n  select type(x)\n    type is (integer)\n      y = 1\n    class default\n      y = 0\n  end select\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:179
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:180
require.NoError(t, perr, "danmuji:180: given labeled block constructs > when parsing unlabeled SELECT TYPE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:181
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:181: given labeled block constructs > when parsing unlabeled SELECT TYPE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Failing repro (as of 2026-04-11): labeled SELECT CASE. Baseline
	// sample 13 essence, minimized. The trailing `sign_case` after
	// END SELECT is the key signal — parser must keep `end select`
	// shift path alive rather than reducing the inner statement list
	// with `end` as a trailing identifier.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:190
t.Run("parsing labeled SELECT CASE", func(t *testing.T) {
			src := "program t\n  sign_case: SELECT CASE (n)\n  CASE DEFAULT\n    m = 0\n  END SELECT sign_case\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:194
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:195
require.NoError(t, perr, "danmuji:195: given labeled block constructs > when parsing labeled SELECT CASE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:196
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:196: given labeled block constructs > when parsing labeled SELECT CASE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Failing repro (as of 2026-04-11): labeled SELECT TYPE. Combined
	// shape for the split oracle fix target — if this passes, both s11
	// and s13 shapes are covered by the same state split.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:203
t.Run("parsing labeled SELECT TYPE", func(t *testing.T) {
			src := "program t\n  sel: select type(x)\n    type is (integer)\n      y = 1\n  end select sel\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:207
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:208
require.NoError(t, perr, "danmuji:208: given labeled block constructs > when parsing labeled SELECT TYPE > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:209
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:209: given labeled block constructs > when parsing labeled SELECT TYPE > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Real-corpus sample 23: labeled IF with nested ELSE IF branches
	// and an internal labeled-IF-start-expression on the ELSE IF line.
	// The critical shape is `ELSE IF (...) THEN cond1` where `cond1`
	// is the trailing label, NOT a new block label start.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:217
t.Run("parsing labeled IF with ELSE IF chain and trailing label", func(t *testing.T) {
			src := "PROGRAM TEST\n  cond1: IF (y < 0) THEN\n     y = 9\n  ELSE IF (x > 0) THEN cond1\n     r = 9\n  ELSE cond1\n    y = 10\n  END IF cond1\nEND PROGRAM\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:221
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:222
require.NoError(t, perr, "danmuji:222: given labeled block constructs > when parsing labeled IF with ELSE IF chain and trailing label > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:223
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:223: given labeled block constructs > when parsing labeled IF with ELSE IF chain and trailing label > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Real-corpus sample 22: SELECT CASE body containing preproc #ifdef
	// blocks that wrap case branches. The preproc blocks must not
	// interfere with the shift/reduce decision at the case-body
	// completion state.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:231
t.Run("parsing SELECT CASE with preproc ifdef inside body", func(t *testing.T) {
			src := "program t\n  select case (x)\n#ifdef FOO\n  case (1)\n    y = 1\n#endif\n  case default\n    y = 0\n  end select\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:235
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:236
require.NoError(t, perr, "danmuji:236: given labeled block constructs > when parsing SELECT CASE with preproc ifdef inside body > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:237
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:237: given labeled block constructs > when parsing SELECT CASE with preproc ifdef inside body > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Real-corpus sample 22 (full): multiple #ifdef/#if branches inside
	// a SELECT CASE body, including one with a relational expression
	// in the preproc condition (#if TEST > 0). The parser fails here
	// on the preproc relational expression inside case body.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:245
t.Run("parsing SELECT CASE with multiple preproc conditions (sample 22 full)", func(t *testing.T) {
			src := "program case_preprocessor\n    implicit none\n    character(len=256) :: multidata_item\n    integer :: dim\n    multidata_item = \"test\"\n\n    select case (multidata_item)\n#ifdef UM_PHYSICS\n        case ('plant_func_types')\n                dim = 1\n#endif\n#if TEST > 0\n        case ('test')\n                dim = 1\n#endif\n        case default\n#ifdef HAVE_DEFAULT_BODY\n                dim = 1\n#endif\n    end select\n\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:249
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:250
require.NoError(t, perr, "danmuji:250: given labeled block constructs > when parsing SELECT CASE with multiple preproc conditions (sample 22 full) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:251
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:251: given labeled block constructs > when parsing SELECT CASE with multiple preproc conditions (sample 22 full) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Real-corpus sample 23 (full): multiple IF variants, labeled and
	// unlabeled, with nested ELSE IF branches. Full text from the
	// tree-sitter-fortran test corpus.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:258
t.Run("parsing multi-IF block with labels (sample 23 full)", func(t *testing.T) {
			src := "PROGRAM TEST\n  IF (x<7) y = 9\n  if(ix.ge.1.and.2.le.nx)x=1.4\n\n  IF (arg(1:1) == ADJUSTL(' r')) THEN\n    r = 0\n  ELSE IF (arg(1:1) .NE. CHAR(l(1))) THEN\n    l = 67\n  ELSE IF (arg(1:1) .NE. CHAR(m(1))) THEN\n  ELSE\n    n = 0\n  ENDIF\n\n  cond1: IF (y < 0) THEN\n     y = 9\n  ELSE  IF (x > 0) THEN cond1\n   r = 9\n   IF (arg(1:1)) THEN\n     r = 0\n   ELSE\n     n = 0\n   END IF\n  ELSE cond1\n    y = 10\n  END IF cond1\nEND PROGRAM\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:262
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:263
require.NoError(t, perr, "danmuji:263: given labeled block constructs > when parsing multi-IF block with labels (sample 23 full) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:264
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:264: given labeled block constructs > when parsing multi-IF block with labels (sample 23 full) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Real-corpus sample 7: keyword `data` used as a variable name in
	// `data(n) = 54`. The parser must keep both interpretations (data
	// statement vs identifier-as-keyword call expression) as a runtime
	// GLR fork.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:272
t.Run("parsing data(n) = 54 keyword as identifier", func(t *testing.T) {
			src := "program t\n  data(n) = 54\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:276
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:277
require.NoError(t, perr, "danmuji:277: given labeled block constructs > when parsing data(n) = 54 keyword as identifier > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:278
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:278: given labeled block constructs > when parsing data(n) = 54 keyword as identifier > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	// Real-corpus sample 7 (full): mix of data statements and
	// keyword-as-identifier expression `data(n) = 54`.
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:284
t.Run("parsing data statements with keyword-as-identifier mix (sample 7 full)", func(t *testing.T) {
			src := "program test\n  data a, b /1, 2/, c /3, 4/d/5,6/\n  data list / null() /\n  data bool / .true. /\n  data foo%bar / \"hello\" /\n  DATA person / Person_t(42, \"Test Name\") /\n  DATA (array(1,k),k=1,n) /3.14e-3, -42.5/\n  DATA array(:, N) / &\n    54.45_fp, 200.01_fp /\n  DATA complex_array / ( 0, 1 ), ( 1, 0 ) /\n  DATA foo / 3 * 0.0, 4 * bar, 1.0, 2.0 /\n  data params/ param1, param2/\n\n  ! comment block\n  x = 4\n\n  ! Check data is still ok as identifier\n  data(n) = 54\nend program test\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:288
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:289
require.NoError(t, perr, "danmuji:289: given labeled block constructs > when parsing data statements with keyword-as-identifier mix (sample 7 full) > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:290
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:290: given labeled block constructs > when parsing data statements with keyword-as-identifier mix (sample 7 full) > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:295
t.Run("generic operator bindings", func(t *testing.T) {
	const grammarPath = "/home/draco/grammar_parity_ro/fortran/src/grammar.json"
	data, err := os.ReadFile(grammarPath)
	if err != nil {
			t.Skipf("skip: %s not available", grammarPath)
		}
	g, gerr := ImportGrammarJSON(data)
	if gerr != nil {
			t.Fatalf("ImportGrammarJSON: %v", gerr)
		}
	lang, lerr := GenerateLanguage(g)
	if lerr != nil {
			t.Fatalf("GenerateLanguage: %v", lerr)
		}
	grammars.AdaptScannerForLanguage("fortran", lang)
	parser := gotreesitter.NewParser(lang)
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:296
t.Run("parsing assignment(=) generic", func(t *testing.T) {
			src := "program test\n  type, public :: t\n    real :: x\n    contains\n       generic, private :: assignment(=) => assign_method\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:300
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:301
require.NoError(t, perr, "danmuji:301: given generic operator bindings > when parsing assignment(=) generic > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:302
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:302: given generic operator bindings > when parsing assignment(=) generic > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
	//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:306
t.Run("parsing operator(+) generic", func(t *testing.T) {
			src := "program test\n  type, public :: t\n    real :: x\n    contains\n       generic, private :: operator(+) => add_method\n  end type\nend program\n"
			tree, perr := parser.Parse([]byte(src))

			//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:310
t.Run("parse succeeds", func(t *testing.T) {
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:311
require.NoError(t, perr, "danmuji:311: given generic operator bindings > when parsing operator(+) generic > then parse succeeds | expect (expect perr == nil)")
				//line /home/draco/work/gotreesitter/.claude/worktrees/fortran/grammargen/fortran_parity.dmj:312
assert.Equal(t, false, tree.RootNode().HasError(), "danmuji:312: given generic operator bindings > when parsing operator(+) generic > then parse succeeds | expect (expect tree.RootNode().HasError() == false)")
			})
		})
})
}

