package grammargen

import (
	"encoding/json"
	"fmt"
	"strings"
)

func applyImportGrammarShapeHints(g *Grammar) {
	if g == nil {
		return
	}
	switch g.Name {
	case "javascript", "typescript", "tsx", "sql":
		// These grammars rely heavily on tree-sitter's binary repeat helper
		// shape. Keeping the upstream lowering avoids large state blowups and
		// preserves upstream ambiguity handling for imported grammars.
		g.BinaryRepeatMode = true
	case "fortran":
		// The imported Fortran grammar benefits from upstream-style repeat
		// lowering, and aggressively extracting wide SEQ branches trims a large
		// amount of avoidable state growth without changing the remaining known
		// failure modes in the focused diagnostics.
		g.BinaryRepeatMode = true
		g.SeqChoiceHelperThreshold = 1
	}
}

// ImportGrammarJSON parses a tree-sitter grammar.json file (the canonical
// resolved form generated by `tree-sitter generate`) and returns a Grammar IR.
// This is more reliable than ImportGrammarJS because grammar.json has no
// require() calls, helper functions, or other JavaScript-specific constructs.
func ImportGrammarJSON(data []byte) (*Grammar, error) {
	var raw jsonGrammar
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse grammar.json: %w", err)
	}

	g := NewGrammar(raw.Name)
	applyImportGrammarShapeHints(g)

	// Build named precedence → numeric value mapping from the precedences array.
	// Each level is an ordered list from highest to lowest precedence.
	// STRING entries define named precedence values.
	namedPrecs := buildNamedPrecMap(raw.Precedences)

	// Store the full precedences table (including SYMBOL entries) for use
	// during LR conflict resolution. SYMBOL entries define rule-level
	// precedence ordering (e.g. update_expression > logical_and) that
	// cannot be captured by numeric prec values alone.
	g.Precedences = importPrecedenceLevels(raw.Precedences)

	conv := &jsonConverter{namedPrecs: namedPrecs}

	// Import rules in order.
	for _, name := range raw.ruleOrder {
		rule, err := conv.convertRule(raw.Rules[name])
		if err != nil {
			return nil, fmt.Errorf("rule %q: %w", name, err)
		}
		g.Define(name, rule)
	}

	// Import extras.
	for _, extra := range raw.Extras {
		rule, err := conv.convertRule(extra)
		if err != nil {
			return nil, fmt.Errorf("extras: %w", err)
		}
		g.Extras = append(g.Extras, rule)
	}

	// Import conflicts.
	for _, group := range raw.Conflicts {
		var names []string
		for _, sym := range group {
			names = append(names, sym)
		}
		if len(names) > 0 {
			g.Conflicts = append(g.Conflicts, names)
		}
	}

	// Import externals.
	for _, ext := range raw.Externals {
		rule, err := conv.convertRule(ext)
		if err != nil {
			return nil, fmt.Errorf("externals: %w", err)
		}
		g.Externals = append(g.Externals, rule)
	}

	// Import inline rules.
	g.Inline = raw.Inline

	// Import word token.
	if raw.Word != "" {
		g.Word = raw.Word
	}

	// Import reserved word sets in source order. The first set is the global
	// reserved set in tree-sitter's grammar.json format.
	for _, name := range raw.reservedOrder {
		members := raw.Reserved[name]
		rules := make([]*Rule, 0, len(members))
		for _, member := range members {
			rule, err := conv.convertRule(member)
			if err != nil {
				return nil, fmt.Errorf("reserved %q: %w", name, err)
			}
			rules = append(rules, rule)
		}
		g.ReservedWordSets = append(g.ReservedWordSets, ReservedWordSet{
			Name:  name,
			Rules: rules,
		})
	}

	// Import supertypes.
	g.Supertypes = raw.Supertypes

	applyPostImportShapeHints(g)

	return g, nil
}

// applyPostImportShapeHints runs after all rules, extras, conflicts, and
// externals have been imported. This is where rule-mutating shape hints go
// (distinct from applyImportGrammarShapeHints which only touches flags
// before rules exist).
func applyPostImportShapeHints(g *Grammar) {
	if g == nil {
		return
	}
	switch g.Name {
	case "fortran":
		// Wrap SELECT-body statement rules with a positive precedence so
		// their completing reduce outranks the closure-derived identifier-
		// as-keyword shift at the end of a case body.
		//
		// Context (diagnosed 2026-04-11 via GLR trace + kernel item dump):
		// State 8608 (gen) has two actions on lookahead `end`:
		//   REDUCE case_statement → case default _case_statement_seq_choice116
		//          case_statement_repeat123 .  (from kernel item dot=4)
		//   SHIFT end → <identifier-reduce state>  (from closure item
		//          identifier → . end, one of identifier's 66 keyword alts)
		// Both productions carry prec=0 so default-yacc behavior picks
		// shift, landing us in a state that only reduces to identifier on
		// every lookahead including `select`. With no action on `select`
		// beyond that, all GLR stacks die.
		//
		// Wrapping case_statement / type_statement / rank_statement with
		// PREC gives the reduce a nonzero precedence so it wins the S/R
		// conflict. The body-statement productions then close cleanly
		// before `end` is shifted, letting the parser enter the
		// end_select_statement continuation state with `end select`
		// properly matched.
		// Must outrank prec=100 which propagates to the identifier shift
		// via the expression wrapper chain. The same conflict shape appears
		// at every "block body intermediate" nonterminal whose completing
		// reduce races with an identifier-as-keyword shift on `end`.
		wrapRuleWithPrec(g, "case_statement", 200)
		wrapRuleWithPrec(g, "type_statement", 200)
		wrapRuleWithPrec(g, "rank_statement", 200)
		wrapRuleWithPrec(g, "else_clause", 200)
		wrapRuleWithPrec(g, "elseif_clause", 200)
		wrapRuleWithPrec(g, "elsewhere_clause", 200)
		// Block-statement rules: outrank inline-IF / inline-WHERE GLR forks
		// so the parser commits to the block interpretation when THEN/keyword
		// is seen, instead of letting the inline interpretation linger and
		// later misparse the body.
		wrapRuleWithPrec(g, "_block_if_statement", 200)
		wrapRuleWithPrec(g, "_block_where_statement", 200)
		wrapRuleWithPrec(g, "_block_forall_statement", 200)
		// Inline forms get LOW prec so the block form wins any GLR fork
		// where both interpretations are alive at the same parse point.
		wrapRuleWithPrec(g, "_inline_if_statement", -10)
		wrapRuleWithPrec(g, "_inline_where_statement", -10)
		wrapRuleWithPrec(g, "_inline_forall_statement", -10)
		// Identifier keyword aliases (`if`, `then`, `endif`, ...) get strongly
		// negative prec so any other interpretation wins GLR forks.
		deprioritizeKeywordIdentifierAlts(g)
		// Strip `identifier` from declared conflict groups so precedence
		// (above) actually fires instead of being short-circuited by the
		// shiftReduceInConflictGroup fallback. (Order matters: this must
		// run BEFORE we re-add identifier-conflict groups for keyword-as-
		// variable cases below.)
		removeIdentifierFromConflictGroups(g)
		// Declare a conflict group between statement-keyword rules and
		// identifier so that the post-shift state for `data` (and similar
		// keywords usable as identifiers in expression contexts like
		// `data(n) = 54`) keeps the `(` shift/reduce conflict as GLR.
		// Without this, precedence resolution drops the
		// `identifier → data` reduce in favor of the shift, killing the
		// expression-context parse. Tested 2026-04-11 to fix sample 7
		// without affecting normal `data` statement parsing.
		g.Conflicts = append(g.Conflicts,
			[]string{"data_statement", "identifier"},
			[]string{"call_expression", "identifier"},
		)
		// inline_preproc_comment uses `\/\/.*` upstream which collides with
		// Fortran's `//` string concat operator. Narrow it.
		narrowInlinePreprocComment(g)
		replaceNewlineLiteralInPreprocIfs(g)
	}
}

// wrapRuleWithPrec wraps g.Rules[name] in a Prec(n, ...) wrapper, preserving
// any existing outer wrappers. No-op if the rule is missing.
func wrapRuleWithPrec(g *Grammar, name string, prec int) {
	rule, ok := g.Rules[name]
	if !ok || rule == nil {
		return
	}
	g.Rules[name] = Prec(prec, rule)
}

// narrowInlinePreprocComment effectively disables the `inline_preproc_comment`
// rule by replacing its PATTERN with one that cannot match. The upstream rule
// uses `\/\/.*` to recognize C-style line comments inside preproc directives,
// but in Fortran `//` is also the string concatenation operator. The
// over-broad pattern eats `// "b"` mid-expression, killing parses that use
// string concat. References to this rule appear in CHOICE positions with
// BLANK alternatives (i.e. the comment is optional), so disabling the
// pattern means those positions silently take BLANK and parsing continues.
// Real preproc line comments (rare in practice) are then unrecognized but
// no Fortran corpus we test relies on them.
func narrowInlinePreprocComment(g *Grammar) {
	rule, ok := g.Rules["inline_preproc_comment"]
	if !ok || rule == nil || rule.Kind != RulePattern {
		return
	}
	// Pattern that never matches anything (impossible position assertion).
	g.Rules["inline_preproc_comment"] = Pat(`a^never_matches`)
}

// removeIdentifierFromConflictGroups strips `identifier` from any declared
// conflict group. The upstream Fortran grammar declares
// `[_inline_if_statement, arithmetic_if_statement, _block_if_statement, identifier]`
// as a conflict group, which causes grammargen's shiftReduceInConflictGroup
// fallback to keep S/R conflicts between IF rules and `identifier → keyword`
// reduces as GLR. Combined with the keyword-as-identifier ambiguity, this
// makes the wrong fork survive in cases like `IF (a==1) THEN r = 0 ENDIF`.
// Removing `identifier` from these groups lets precedence (set by
// deprioritizeKeywordIdentifierAlts) cleanly resolve the conflicts.
func removeIdentifierFromConflictGroups(g *Grammar) {
	for i, group := range g.Conflicts {
		if len(group) <= 1 {
			continue
		}
		hasIdentifier := false
		for _, name := range group {
			if name == "identifier" {
				hasIdentifier = true
				break
			}
		}
		if !hasIdentifier {
			continue
		}
		var filtered []string
		for _, name := range group {
			if name != "identifier" {
				filtered = append(filtered, name)
			}
		}
		g.Conflicts[i] = filtered
	}
}

// deprioritizeKeywordIdentifierAlts walks the `identifier` rule (a CHOICE
// of N alternatives, mostly ALIAS(pattern, "keyword") alts of Fortran
// keywords-as-identifiers) and wraps every alt whose alias value is in the
// fortranKeywordAliasesToDeprioritize set with PREC(-100). The intent: in
// any GLR fork or shift/reduce conflict where identifier-as-keyword vs
// real-keyword interpretation compete, the identifier path loses. Fortran
// allows keywords as variable names, but in practice block-statement
// keywords (`if`, `then`, `else`, `endif`, `end`, `select`, `case`, ...)
// almost never appear as identifiers — and when they do, the parser fall
// back via runtime GLR works because precedence-tied reduces are kept.
func deprioritizeKeywordIdentifierAlts(g *Grammar) {
	rule, ok := g.Rules["identifier"]
	if !ok || rule == nil || rule.Kind != RuleChoice {
		return
	}
	deprioritize := map[string]bool{
		"if": true, "then": true, "else": true, "elseif": true, "endif": true,
		"end": true, "endprogram": true, "endmodule": true, "endsubroutine": true,
		"endfunction": true, "endsubmodule": true, "endinterface": true,
		"endtype": true, "enddo": true, "endwhere": true, "endselect": true,
		"endenum": true, "endenumeration": true, "endassociate": true,
		"endblock": true, "endblockdata": true, "endcritical": true,
		"endforall": true, "endprocedure": true,
		"select": true, "selectcase": true, "selecttype": true, "selectrank": true,
		"case": true, "where": true, "elsewhere": true, "endwhere2": true,
		"do": true, "while": true, "forall": true,
	}
	newAlts := make([]*Rule, len(rule.Children))
	for i, alt := range rule.Children {
		if alt != nil && alt.Kind == RuleAlias && deprioritize[alt.Value] {
			newAlts[i] = Prec(-100, alt)
		} else {
			newAlts[i] = alt
		}
	}
	out := *rule
	out.Children = newAlts
	g.Rules["identifier"] = &out
}

// replaceNewlineLiteralInPreprocIfs walks every preproc_if_in_*  and
// preproc_ifdef_in_* rule and replaces the literal "\n" STRING terminator
// (used by tree-sitter-fortran upstream as the header terminator after the
// condition expression) with a CHOICE between that literal and the
// _external_end_of_statement SYMBOL. Fortran's external scanner produces
// _external_end_of_statement when it sees a newline in these contexts, and
// without this rewrite the parser state's lookahead lacks
// _external_end_of_statement, killing the parse as soon as the condition
// line ends. The equivalent substitution is already implicit in how
// `_end_of_statement → ; | _external_end_of_statement` is used elsewhere.
func replaceNewlineLiteralInPreprocIfs(g *Grammar) {
	for name, rule := range g.Rules {
		if !strings.HasPrefix(name, "preproc_if") && !strings.HasPrefix(name, "preproc_ifdef") {
			continue
		}
		g.Rules[name] = replaceNewlineLiteralInRule(rule)
	}
}

// replaceNewlineLiteralInRule recursively walks a rule tree and substitutes
// any top-level STRING("\n") leaf with CHOICE(STRING("\n"), SYMBOL("_external_end_of_statement")).
func replaceNewlineLiteralInRule(r *Rule) *Rule {
	if r == nil {
		return nil
	}
	if r.Kind == RuleString && r.Value == "\n" {
		return Choice(Str("\n"), Sym("_external_end_of_statement"))
	}
	if len(r.Children) == 0 {
		return r
	}
	changed := false
	newChildren := make([]*Rule, len(r.Children))
	for i, c := range r.Children {
		nc := replaceNewlineLiteralInRule(c)
		if nc != c {
			changed = true
		}
		newChildren[i] = nc
	}
	if !changed {
		return r
	}
	out := *r
	out.Children = newChildren
	return &out
}

// buildPrecMaps builds two precedence maps from the precedences array:
//   - namedPrecs: STRING entry name → numeric value (for resolving named precs
//     like "logical_and" used in PREC_LEFT("logical_and", ...))
//   - symbolPrecs: SYMBOL entry name → numeric value (for overriding the outer
//     PREC value of entire rules like update_expression)
//
// buildNamedPrecMap builds a mapping from named precedence strings to numeric
// values. Levels are ordered from highest to lowest precedence; within each
// level, earlier entries have higher precedence. Values are assigned globally
// across all levels so that entries in earlier levels always outrank entries
// in later levels.
func buildNamedPrecMap(rawLevels []json.RawMessage) map[string]int {
	// First pass: collect all STRING entries across all levels in order.
	type precEntry struct {
		name      string
		globalIdx int
	}
	var all []precEntry
	for _, rawLevel := range rawLevels {
		var entries []jsonPrecEntry
		if err := json.Unmarshal(rawLevel, &entries); err != nil {
			continue
		}
		for _, entry := range entries {
			if entry.Type == "STRING" && entry.Value != "" {
				all = append(all, precEntry{name: entry.Value, globalIdx: len(all)})
			}
		}
	}

	// Second pass: assign values so first entry gets highest value.
	m := make(map[string]int, len(all))
	total := len(all)
	for _, e := range all {
		val := total - 1 - e.globalIdx
		if existing, ok := m[e.name]; !ok || val > existing {
			m[e.name] = val
		}
	}
	return m
}

// importPrecedenceLevels converts raw JSON precedence levels into the Grammar
// IR's PrecEntry format.
func importPrecedenceLevels(rawLevels []json.RawMessage) [][]PrecEntry {
	var levels [][]PrecEntry
	for _, rawLevel := range rawLevels {
		var entries []jsonPrecEntry
		if err := json.Unmarshal(rawLevel, &entries); err != nil {
			continue
		}
		var level []PrecEntry
		for _, e := range entries {
			switch {
			case e.Type == "STRING" && e.Value != "":
				level = append(level, PrecEntry{Name: e.Value})
			case e.Type == "SYMBOL" && e.Name != "":
				level = append(level, PrecEntry{IsSymbol: true, Name: e.Name})
			}
		}
		if len(level) > 0 {
			levels = append(levels, level)
		}
	}
	return levels
}

// jsonGrammar is the top-level structure of a grammar.json file.
type jsonGrammar struct {
	Name          string                       `json:"name"`
	Rules         map[string]json.RawMessage   `json:"rules"`
	Extras        []json.RawMessage            `json:"extras"`
	Conflicts     [][]string                   `json:"conflicts"`
	Externals     []json.RawMessage            `json:"externals"`
	Inline        []string                     `json:"inline"`
	Supertypes    []string                     `json:"supertypes"`
	Word          string                       `json:"word"`
	Reserved      map[string][]json.RawMessage `json:"reserved"`
	Precedences   []json.RawMessage            `json:"precedences"`
	ruleOrder     []string                     // populated during UnmarshalJSON
	reservedOrder []string                     // populated during UnmarshalJSON
}

// jsonPrecEntry is an entry in the precedences array.
type jsonPrecEntry struct {
	Type  string `json:"type"`
	Value string `json:"value"` // for STRING entries
	Name  string `json:"name"`  // for SYMBOL entries
}

// UnmarshalJSON implements custom unmarshaling to preserve rule order.
func (g *jsonGrammar) UnmarshalJSON(data []byte) error {
	// First pass: use a decoder to extract rule order.
	type Alias jsonGrammar
	if err := json.Unmarshal(data, (*Alias)(g)); err != nil {
		return err
	}

	// Second pass: extract rule order from the raw JSON.
	// json.Decoder preserves object key order.
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if rulesRaw, ok := raw["rules"]; ok {
		g.ruleOrder = extractKeyOrder(rulesRaw)
	}
	if reservedRaw, ok := raw["reserved"]; ok {
		g.reservedOrder = extractKeyOrder(reservedRaw)
	}

	return nil
}

// extractKeyOrder extracts the key order from a JSON object.
func extractKeyOrder(data json.RawMessage) []string {
	dec := json.NewDecoder(jsonReader(data))
	t, err := dec.Token()
	if err != nil || t != json.Delim('{') {
		return nil
	}

	var keys []string
	for dec.More() {
		t, err := dec.Token()
		if err != nil {
			break
		}
		key, ok := t.(string)
		if !ok {
			break
		}
		keys = append(keys, key)
		// Skip the value.
		var skip json.RawMessage
		if err := dec.Decode(&skip); err != nil {
			break
		}
	}
	return keys
}

// jsonReader wraps a byte slice to implement io.Reader.
type jsonReaderImpl struct {
	data []byte
	pos  int
}

func jsonReader(data []byte) *jsonReaderImpl {
	return &jsonReaderImpl{data: data}
}

func (r *jsonReaderImpl) Read(p []byte) (int, error) {
	if r.pos >= len(r.data) {
		return 0, fmt.Errorf("EOF")
	}
	n := copy(p, r.data[r.pos:])
	r.pos += n
	return n, nil
}

// jsonRuleNode is the JSON representation of a rule node.
type jsonRuleNode struct {
	Type    string            `json:"type"`
	Value   interface{}       `json:"value"`   // string for STRING/PATTERN, int for PREC*
	Name    string            `json:"name"`    // for SYMBOL, FIELD
	Content json.RawMessage   `json:"content"` // for wrappers (TOKEN, PREC*, REPEAT, etc.)
	Members []json.RawMessage `json:"members"` // for SEQ, CHOICE
	Named   bool              `json:"named"`   // for ALIAS
	Flags   string            `json:"flags"`   // for PATTERN: "i" = case-insensitive
}

// jsonConverter holds context for converting grammar.json rules.
type jsonConverter struct {
	namedPrecs map[string]int // named precedence → numeric value
}

// convertRule converts a grammar.json rule node to a Grammar Rule.
func (c *jsonConverter) convertRule(data json.RawMessage) (*Rule, error) {
	var node jsonRuleNode
	if err := json.Unmarshal(data, &node); err != nil {
		return nil, fmt.Errorf("unmarshal rule: %w", err)
	}

	switch node.Type {
	case "STRING":
		val, ok := node.Value.(string)
		if !ok {
			return nil, fmt.Errorf("STRING value not a string: %v", node.Value)
		}
		return Str(val), nil

	case "PATTERN":
		val, ok := node.Value.(string)
		if !ok {
			return nil, fmt.Errorf("PATTERN value not a string: %v", node.Value)
		}
		if strings.Contains(node.Flags, "i") {
			val = makeCaseInsensitivePattern(val)
		}
		return Pat(val), nil

	case "SYMBOL":
		return Sym(node.Name), nil

	case "BLANK":
		return Blank(), nil

	case "SEQ":
		children, err := c.convertRuleList(node.Members)
		if err != nil {
			return nil, fmt.Errorf("SEQ: %w", err)
		}
		return Seq(children...), nil

	case "CHOICE":
		children, err := c.convertRuleList(node.Members)
		if err != nil {
			return nil, fmt.Errorf("CHOICE: %w", err)
		}
		return Choice(children...), nil

	case "REPEAT":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("REPEAT: %w", err)
		}
		return Repeat(child), nil

	case "REPEAT1":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("REPEAT1: %w", err)
		}
		return Repeat1(child), nil

	case "TOKEN":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("TOKEN: %w", err)
		}
		return Token(child), nil

	case "IMMEDIATE_TOKEN":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("IMMEDIATE_TOKEN: %w", err)
		}
		return ImmToken(child), nil

	case "PREC":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return Prec(n, r)
		})

	case "PREC_LEFT":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return PrecLeft(n, r)
		})

	case "PREC_RIGHT":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return PrecRight(n, r)
		})

	case "PREC_DYNAMIC":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return PrecDynamic(n, r)
		})

	case "FIELD":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("FIELD: %w", err)
		}
		return Field(node.Name, child), nil

	case "ALIAS":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("ALIAS: %w", err)
		}
		val, ok := node.Value.(string)
		if !ok {
			return nil, fmt.Errorf("ALIAS value not a string: %v", node.Value)
		}
		return Alias(child, val, node.Named), nil

	case "RESERVED":
		// RESERVED wraps a rule with context-dependent keyword reservation.
		// We unwrap it — the structural grammar encodes the context, and our
		// runtime parser handles keyword promotion separately.
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("RESERVED: %w", err)
		}
		return child, nil

	default:
		return nil, fmt.Errorf("unsupported rule type %q", node.Type)
	}
}

// convertPrecRule handles PREC/PREC_LEFT/PREC_RIGHT/PREC_DYNAMIC nodes.
// Resolves named precedence strings to numeric values via the namedPrecs map.
func (c *jsonConverter) convertPrecRule(node jsonRuleNode, make_ func(int, *Rule) *Rule) (*Rule, error) {
	prec := 0
	switch v := node.Value.(type) {
	case float64:
		prec = int(v)
	case int:
		prec = v
	case string:
		if val, ok := c.namedPrecs[v]; ok {
			prec = val
		}
	}

	child, err := c.convertRule(node.Content)
	if err != nil {
		return nil, err
	}
	return make_(prec, child), nil
}

// convertRuleList converts a list of JSON rule nodes to Rules.
func (c *jsonConverter) convertRuleList(members []json.RawMessage) ([]*Rule, error) {
	rules := make([]*Rule, len(members))
	for i, m := range members {
		r, err := c.convertRule(m)
		if err != nil {
			return nil, fmt.Errorf("[%d]: %w", i, err)
		}
		rules[i] = r
	}
	return rules, nil
}

// makeCaseInsensitivePattern converts a regex pattern to case-insensitive form
// by expanding ASCII letters to character classes. For example, "DUP" becomes
// "[Dd][Uu][Pp]". Characters inside character classes are expanded in-place.
func makeCaseInsensitivePattern(pattern string) string {
	var b strings.Builder
	b.Grow(len(pattern) * 4)
	inClass := false
	escaped := false
	for _, ch := range pattern {
		if escaped {
			b.WriteRune(ch)
			escaped = false
			continue
		}
		if ch == '\\' {
			b.WriteRune(ch)
			escaped = true
			continue
		}
		if ch == '[' {
			inClass = true
			b.WriteRune(ch)
			continue
		}
		if ch == ']' {
			inClass = false
			b.WriteRune(ch)
			continue
		}
		if isASCIILetter(ch) {
			if inClass {
				// Inside a character class, add both cases
				lo := rune(ch | 0x20)
				up := rune(ch &^ 0x20)
				b.WriteRune(lo)
				b.WriteRune(up)
			} else {
				// Outside a class, wrap in a class
				lo := rune(ch | 0x20)
				up := rune(ch &^ 0x20)
				b.WriteRune('[')
				b.WriteRune(lo)
				b.WriteRune(up)
				b.WriteRune(']')
			}
		} else {
			b.WriteRune(ch)
		}
	}
	return b.String()
}

func isASCIILetter(ch rune) bool {
	return (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z')
}
