package grammargen

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ImportGrammarJSON parses a tree-sitter grammar.json file (the canonical
// resolved form generated by `tree-sitter generate`) and returns a Grammar IR.
// This is more reliable than ImportGrammarJS because grammar.json has no
// require() calls, helper functions, or other JavaScript-specific constructs.
func ImportGrammarJSON(data []byte) (*Grammar, error) {
	var raw jsonGrammar
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse grammar.json: %w", err)
	}

	g := NewGrammar(raw.Name)

	// Build precedence mappings from the precedences array.
	pm := buildPrecMaps(raw.Precedences)

	conv := &jsonConverter{namedPrecs: pm.namedPrecs}

	// Import rules in order.
	for _, name := range raw.ruleOrder {
		rule, err := conv.convertRule(raw.Rules[name])
		if err != nil {
			return nil, fmt.Errorf("rule %q: %w", name, err)
		}
		g.Define(name, rule)
	}

	// Import extras.
	for _, extra := range raw.Extras {
		rule, err := conv.convertRule(extra)
		if err != nil {
			return nil, fmt.Errorf("extras: %w", err)
		}
		g.Extras = append(g.Extras, rule)
	}

	// Import conflicts.
	for _, group := range raw.Conflicts {
		var names []string
		for _, sym := range group {
			names = append(names, sym)
		}
		if len(names) > 0 {
			g.Conflicts = append(g.Conflicts, names)
		}
	}

	// Import externals.
	for _, ext := range raw.Externals {
		rule, err := conv.convertRule(ext)
		if err != nil {
			return nil, fmt.Errorf("externals: %w", err)
		}
		g.Externals = append(g.Externals, rule)
	}

	// Import inline rules.
	g.Inline = raw.Inline

	// Import word token.
	if raw.Word != "" {
		g.Word = raw.Word
	}

	// Import supertypes.
	g.Supertypes = raw.Supertypes

	// Import precedence orderings for direct ordering comparison during
	// LR conflict resolution (mirroring tree-sitter C's compare_precedence).
	g.PrecOrderings = buildPrecOrderings(raw.Precedences)

	// Apply implicit precedences from SYMBOL entries in the precedences
	// array. Tree-sitter C assigns an implicit precedence to all productions
	// of a rule when that rule's symbol appears in the precedences array.
	// For rules WITHOUT explicit prec wrappers, wrap with Prec() so
	// normalization propagates the implicit value to productions.
	// For rules WITH explicit prec wrappers, skip — tree-sitter C keeps
	// implicit prec as a SEPARATE tiebreaker from production prec; modifying
	// the explicit wrapper's value would conflate the two mechanisms.
	for symName, precVal := range pm.symbolPrecs {
		rule, ok := g.Rules[symName]
		if !ok {
			continue
		}
		switch rule.Kind {
		case RulePrec, RulePrecLeft, RulePrecRight, RulePrecDynamic:
			// Rule already has an explicit prec wrapper — don't modify it.
			// The ordering comparison (compareReducesByOrdering) handles
			// implicit prec for these rules via the PrecOrderings array.
		default:
			g.Rules[symName] = Prec(precVal, rule)
		}
	}

	return g, nil
}

// precMaps holds named precedence → numeric value mappings built from the
// grammar's precedences array. namedPrecs maps STRING entries (like
// "binary_plus"), symbolPrecs maps SYMBOL entries (like "arrow_function").
type precMaps struct {
	namedPrecs  map[string]int
	symbolPrecs map[string]int
}

// buildPrecMaps builds mappings from the grammar's precedences array.
// Levels are ordered from highest to lowest precedence; within each
// level, earlier entries have higher precedence. Values are assigned globally
// across all levels so that entries in earlier levels always outrank entries
// in later levels.
//
// STRING entries define named precedence values used by prec.left('name', ...);
// SYMBOL entries assign implicit precedence to all productions of a rule,
// matching tree-sitter C's behavior (e.g., $.arrow_function at the bottom of
// a precedences group gets a low-but-nonzero precedence so it correctly loses
// to binary operators in S/R conflict resolution).
func buildPrecMaps(rawLevels []json.RawMessage) precMaps {
	// First pass: collect ALL entries across all levels in order.
	type precEntry struct {
		name      string
		isSymbol  bool
		globalIdx int
	}
	var all []precEntry
	for _, rawLevel := range rawLevels {
		var entries []jsonPrecEntry
		if err := json.Unmarshal(rawLevel, &entries); err != nil {
			continue
		}
		for _, entry := range entries {
			switch {
			case entry.Type == "STRING" && entry.Value != "":
				all = append(all, precEntry{name: entry.Value, globalIdx: len(all)})
			case entry.Type == "SYMBOL" && entry.Name != "":
				all = append(all, precEntry{name: entry.Name, isSymbol: true, globalIdx: len(all)})
			}
		}
	}

	// Second pass: assign values so first entry gets highest value.
	named := make(map[string]int)
	symbols := make(map[string]int)
	total := len(all)
	for _, e := range all {
		val := total - 1 - e.globalIdx
		if e.isSymbol {
			if existing, ok := symbols[e.name]; !ok || val > existing {
				symbols[e.name] = val
			}
		} else {
			if existing, ok := named[e.name]; !ok || val > existing {
				named[e.name] = val
			}
		}
	}
	return precMaps{namedPrecs: named, symbolPrecs: symbols}
}

// buildPrecOrderings extracts the raw precedence orderings from the grammar's
// precedences array. Each inner array becomes a []PrecOrderEntry preserving
// the original order (earlier = higher precedence within the level).
func buildPrecOrderings(rawLevels []json.RawMessage) [][]PrecOrderEntry {
	var orderings [][]PrecOrderEntry
	for _, rawLevel := range rawLevels {
		var entries []jsonPrecEntry
		if err := json.Unmarshal(rawLevel, &entries); err != nil {
			continue
		}
		var ordering []PrecOrderEntry
		for _, entry := range entries {
			switch {
			case entry.Type == "STRING" && entry.Value != "":
				ordering = append(ordering, PrecOrderEntry{IsSymbol: false, Name: entry.Value})
			case entry.Type == "SYMBOL" && entry.Name != "":
				ordering = append(ordering, PrecOrderEntry{IsSymbol: true, Name: entry.Name})
			}
		}
		if len(ordering) > 0 {
			orderings = append(orderings, ordering)
		}
	}
	return orderings
}

// jsonGrammar is the top-level structure of a grammar.json file.
type jsonGrammar struct {
	Name        string                       `json:"name"`
	Rules       map[string]json.RawMessage   `json:"rules"`
	Extras      []json.RawMessage            `json:"extras"`
	Conflicts   [][]string                   `json:"conflicts"`
	Externals   []json.RawMessage            `json:"externals"`
	Inline      []string                     `json:"inline"`
	Supertypes  []string                     `json:"supertypes"`
	Word        string                       `json:"word"`
	Precedences []json.RawMessage            `json:"precedences"`
	ruleOrder   []string                     // populated during UnmarshalJSON
}

// jsonPrecEntry is an entry in the precedences array.
type jsonPrecEntry struct {
	Type  string `json:"type"`
	Value string `json:"value"` // for STRING entries
	Name  string `json:"name"`  // for SYMBOL entries
}

// UnmarshalJSON implements custom unmarshaling to preserve rule order.
func (g *jsonGrammar) UnmarshalJSON(data []byte) error {
	// First pass: use a decoder to extract rule order.
	type Alias jsonGrammar
	if err := json.Unmarshal(data, (*Alias)(g)); err != nil {
		return err
	}

	// Second pass: extract rule order from the raw JSON.
	// json.Decoder preserves object key order.
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	if rulesRaw, ok := raw["rules"]; ok {
		g.ruleOrder = extractKeyOrder(rulesRaw)
	}

	return nil
}

// extractKeyOrder extracts the key order from a JSON object.
func extractKeyOrder(data json.RawMessage) []string {
	dec := json.NewDecoder(jsonReader(data))
	t, err := dec.Token()
	if err != nil || t != json.Delim('{') {
		return nil
	}

	var keys []string
	for dec.More() {
		t, err := dec.Token()
		if err != nil {
			break
		}
		key, ok := t.(string)
		if !ok {
			break
		}
		keys = append(keys, key)
		// Skip the value.
		var skip json.RawMessage
		if err := dec.Decode(&skip); err != nil {
			break
		}
	}
	return keys
}

// jsonReader wraps a byte slice to implement io.Reader.
type jsonReaderImpl struct {
	data []byte
	pos  int
}

func jsonReader(data []byte) *jsonReaderImpl {
	return &jsonReaderImpl{data: data}
}

func (r *jsonReaderImpl) Read(p []byte) (int, error) {
	if r.pos >= len(r.data) {
		return 0, fmt.Errorf("EOF")
	}
	n := copy(p, r.data[r.pos:])
	r.pos += n
	return n, nil
}

// jsonRuleNode is the JSON representation of a rule node.
type jsonRuleNode struct {
	Type    string            `json:"type"`
	Value   interface{}       `json:"value"`   // string for STRING/PATTERN, int for PREC*
	Name    string            `json:"name"`    // for SYMBOL, FIELD
	Content json.RawMessage   `json:"content"` // for wrappers (TOKEN, PREC*, REPEAT, etc.)
	Members []json.RawMessage `json:"members"` // for SEQ, CHOICE
	Named   bool              `json:"named"`   // for ALIAS
	Flags   string            `json:"flags"`   // for PATTERN: "i" = case-insensitive
}

// jsonConverter holds context for converting grammar.json rules.
type jsonConverter struct {
	namedPrecs map[string]int // named precedence → numeric value
}

// convertRule converts a grammar.json rule node to a Grammar Rule.
func (c *jsonConverter) convertRule(data json.RawMessage) (*Rule, error) {
	var node jsonRuleNode
	if err := json.Unmarshal(data, &node); err != nil {
		return nil, fmt.Errorf("unmarshal rule: %w", err)
	}

	switch node.Type {
	case "STRING":
		val, ok := node.Value.(string)
		if !ok {
			return nil, fmt.Errorf("STRING value not a string: %v", node.Value)
		}
		return Str(val), nil

	case "PATTERN":
		val, ok := node.Value.(string)
		if !ok {
			return nil, fmt.Errorf("PATTERN value not a string: %v", node.Value)
		}
		if strings.Contains(node.Flags, "i") {
			val = makeCaseInsensitivePattern(val)
		}
		return Pat(val), nil

	case "SYMBOL":
		return Sym(node.Name), nil

	case "BLANK":
		return Blank(), nil

	case "SEQ":
		children, err := c.convertRuleList(node.Members)
		if err != nil {
			return nil, fmt.Errorf("SEQ: %w", err)
		}
		return Seq(children...), nil

	case "CHOICE":
		children, err := c.convertRuleList(node.Members)
		if err != nil {
			return nil, fmt.Errorf("CHOICE: %w", err)
		}
		return Choice(children...), nil

	case "REPEAT":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("REPEAT: %w", err)
		}
		return Repeat(child), nil

	case "REPEAT1":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("REPEAT1: %w", err)
		}
		return Repeat1(child), nil

	case "TOKEN":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("TOKEN: %w", err)
		}
		return Token(child), nil

	case "IMMEDIATE_TOKEN":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("IMMEDIATE_TOKEN: %w", err)
		}
		return ImmToken(child), nil

	case "PREC":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return Prec(n, r)
		})

	case "PREC_LEFT":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return PrecLeft(n, r)
		})

	case "PREC_RIGHT":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return PrecRight(n, r)
		})

	case "PREC_DYNAMIC":
		return c.convertPrecRule(node, func(n int, r *Rule) *Rule {
			return PrecDynamic(n, r)
		})

	case "FIELD":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("FIELD: %w", err)
		}
		return Field(node.Name, child), nil

	case "ALIAS":
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("ALIAS: %w", err)
		}
		val, ok := node.Value.(string)
		if !ok {
			return nil, fmt.Errorf("ALIAS value not a string: %v", node.Value)
		}
		return Alias(child, val, node.Named), nil

	case "RESERVED":
		// RESERVED wraps a rule with context-dependent keyword reservation.
		// We unwrap it — the structural grammar encodes the context, and our
		// runtime parser handles keyword promotion separately.
		child, err := c.convertRule(node.Content)
		if err != nil {
			return nil, fmt.Errorf("RESERVED: %w", err)
		}
		return child, nil

	default:
		return nil, fmt.Errorf("unsupported rule type %q", node.Type)
	}
}

// convertPrecRule handles PREC/PREC_LEFT/PREC_RIGHT/PREC_DYNAMIC nodes.
// Resolves named precedence strings to numeric values via the namedPrecs map.
func (c *jsonConverter) convertPrecRule(node jsonRuleNode, make_ func(int, *Rule) *Rule) (*Rule, error) {
	prec := 0
	var precName string
	switch v := node.Value.(type) {
	case float64:
		prec = int(v)
	case int:
		prec = v
	case string:
		precName = v
		if val, ok := c.namedPrecs[v]; ok {
			prec = val
		}
	}

	child, err := c.convertRule(node.Content)
	if err != nil {
		return nil, err
	}
	rule := make_(prec, child)
	if precName != "" {
		rule.Value = precName // Store original named prec for ordering comparison.
	}
	return rule, nil
}

// convertRuleList converts a list of JSON rule nodes to Rules.
func (c *jsonConverter) convertRuleList(members []json.RawMessage) ([]*Rule, error) {
	rules := make([]*Rule, len(members))
	for i, m := range members {
		r, err := c.convertRule(m)
		if err != nil {
			return nil, fmt.Errorf("[%d]: %w", i, err)
		}
		rules[i] = r
	}
	return rules, nil
}

// makeCaseInsensitivePattern converts a regex pattern to case-insensitive form
// by expanding ASCII letters to character classes. For example, "DUP" becomes
// "[Dd][Uu][Pp]". Characters inside character classes are expanded in-place.
func makeCaseInsensitivePattern(pattern string) string {
	var b strings.Builder
	b.Grow(len(pattern) * 4)
	inClass := false
	escaped := false
	for _, ch := range pattern {
		if escaped {
			b.WriteRune(ch)
			escaped = false
			continue
		}
		if ch == '\\' {
			b.WriteRune(ch)
			escaped = true
			continue
		}
		if ch == '[' {
			inClass = true
			b.WriteRune(ch)
			continue
		}
		if ch == ']' {
			inClass = false
			b.WriteRune(ch)
			continue
		}
		if isASCIILetter(ch) {
			if inClass {
				// Inside a character class, add both cases
				lo := rune(ch | 0x20)
				up := rune(ch &^ 0x20)
				b.WriteRune(lo)
				b.WriteRune(up)
			} else {
				// Outside a class, wrap in a class
				lo := rune(ch | 0x20)
				up := rune(ch &^ 0x20)
				b.WriteRune('[')
				b.WriteRune(lo)
				b.WriteRune(up)
				b.WriteRune(']')
			}
		} else {
			b.WriteRune(ch)
		}
	}
	return b.String()
}

func isASCIILetter(ch rune) bool {
	return (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z')
}
